// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC80sT51Cjj3qHv_rrsoKwrDFkGiOHWfuM',
    appId: '1:865455239666:web:a921f4c1349f73ad8bbb6b',
    messagingSenderId: '865455239666',
    projectId: 'stockflow-app-3a2c1',
    authDomain: 'stockflow-app-3a2c1.firebaseapp.com',
    storageBucket: 'stockflow-app-3a2c1.firebasestorage.app',
    measurementId: 'G-7XFJVTYLQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpKtXyvdQciuBkuP-qvkgFf15XP1ddk8M',
    appId: '1:865455239666:android:8d8f23d3301cfe528bbb6b',
    messagingSenderId: '865455239666',
    projectId: 'stockflow-app-3a2c1',
    storageBucket: 'stockflow-app-3a2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMS-KCQ_5XcsOIfs3e04lrcPe5GwR8N8',
    appId: '1:865455239666:ios:e71212649697e51e8bbb6b',
    messagingSenderId: '865455239666',
    projectId: 'stockflow-app-3a2c1',
    storageBucket: 'stockflow-app-3a2c1.firebasestorage.app',
    iosBundleId: 'com.example.stockflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHMS-KCQ_5XcsOIfs3e04lrcPe5GwR8N8',
    appId: '1:865455239666:ios:e71212649697e51e8bbb6b',
    messagingSenderId: '865455239666',
    projectId: 'stockflow-app-3a2c1',
    storageBucket: 'stockflow-app-3a2c1.firebasestorage.app',
    iosBundleId: 'com.example.stockflowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC80sT51Cjj3qHv_rrsoKwrDFkGiOHWfuM',
    appId: '1:865455239666:web:25e96f3090ee279a8bbb6b',
    messagingSenderId: '865455239666',
    projectId: 'stockflow-app-3a2c1',
    authDomain: 'stockflow-app-3a2c1.firebaseapp.com',
    storageBucket: 'stockflow-app-3a2c1.firebasestorage.app',
    measurementId: 'G-Y4EKHMM6W4',
  );

}